name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run build script
      run: node build.js

    - name: Zip build directory
      run: powershell Compress-Archive -Path ./build -DestinationPath build.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: starfish-proxy-build
        path: build.zip
